# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GachagachaCli < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KazuhiroIto0127/gachagacha-cli/releases/download/v0.0.1/gachagacha-cli_Darwin_x86_64.tar.gz"
      sha256 "387854815a45f216febaecd92701792c02ebd5057c744b3a8d4a71fd4a1fd9a1"

      def install
        bin.install "gachagacha-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KazuhiroIto0127/gachagacha-cli/releases/download/v0.0.1/gachagacha-cli_Darwin_arm64.tar.gz"
      sha256 "18a3d81d57f4673faef1432a06a4f23f082672d198d3e019803c66f945b752c5"

      def install
        bin.install "gachagacha-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KazuhiroIto0127/gachagacha-cli/releases/download/v0.0.1/gachagacha-cli_Linux_arm64.tar.gz"
      sha256 "9401721569000b5ffddc1f3df70665fa9e86562b4dadd2dcfc0bb8b68439f004"

      def install
        bin.install "gachagacha-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KazuhiroIto0127/gachagacha-cli/releases/download/v0.0.1/gachagacha-cli_Linux_x86_64.tar.gz"
      sha256 "13a82b9811d7a70bc9618b713b0b7ad0fbc5d7c00712f50b710d0979ee08099c"

      def install
        bin.install "gachagacha-cli"
      end
    end
  end
end
